var VERSION                      = "1.0";
var UPDATE_POWER_INTERVAL        = 5;
var UPDATE_ENERGY_INTERVAL       = 600;
var LARGE_GRAPH_DAY_COUNT        = 5;
var SMALL_GRAPH_DAY_COUNT        = 2;
var MAXIMUM_ENERGY_LOG_DAYS      = 30;
var INITIAL_EVENT_PAGE_DAY_COUNT = 10;
var MAX_EVENT_PAGE_ENTRY_COUNT   = 100;
